/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package id_tp.tp_id_22_23;

import java.awt.Frame;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.jdom2.Document;
import org.jdom2.Element;

/**
 *
 * @author mikae
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
    }
    
    public static boolean AchaNome(String nomeAutor, Document doc) {
        Element raiz;
        raiz = doc.getRootElement();
        List todosAutores = raiz.getChildren("autor");
        boolean found = false;
        for (int i = 0; i < todosAutores.size(); i++) {
            Element autor = (Element) todosAutores.get(i); //obtem livro i da Lista 
            if (autor.getChild("nome").getText().contains(nomeAutor)) {
                found = true;
            }
        }
        if (!found) {
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Warnings = new javax.swing.JDialog();
        ADN = new javax.swing.JDialog();
        ADN_TF1 = new javax.swing.JTextField();
        ADN_TF2 = new javax.swing.JTextField();
        ADN_B = new javax.swing.JButton();
        ADN_Label1 = new javax.swing.JLabel();
        ADN_Lebal2 = new javax.swing.JLabel();
        ANC = new javax.swing.JDialog();
        ANC_TF1 = new javax.swing.JTextField();
        ANC_TF2 = new javax.swing.JTextField();
        ANC_B1 = new javax.swing.JButton();
        ANC_Label1 = new javax.swing.JLabel();
        ANC_Label2 = new javax.swing.JLabel();
        ACJ = new javax.swing.JDialog();
        ACJ_TF1 = new javax.swing.JTextField();
        ACJ_TF2 = new javax.swing.JTextField();
        ACJ_B1 = new javax.swing.JButton();
        ACJ_L1 = new javax.swing.JLabel();
        ACJ_L2 = new javax.swing.JLabel();
        AGL = new javax.swing.JDialog();
        AGL_TF1 = new javax.swing.JTextField();
        AGL_TF2 = new javax.swing.JTextField();
        AGL_B1 = new javax.swing.JButton();
        AGL_L1 = new javax.swing.JLabel();
        AGL_L2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ButtonAdd = new javax.swing.JButton();
        ButtonEliminar = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Inicio = new javax.swing.JMenu();
        Relatorio = new javax.swing.JMenuItem();
        Autores = new javax.swing.JMenuItem();
        Sair = new javax.swing.JMenuItem();
        Menu_XML = new javax.swing.JMenu();
        Autores_XML = new javax.swing.JMenuItem();
        Obras_XML = new javax.swing.JMenuItem();
        EliminarAutor = new javax.swing.JMenuItem();
        AlterarDataNasc = new javax.swing.JMenuItem();
        AlterarNacionalidade = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        AlterarConjuge = new javax.swing.JMenuItem();
        AlterarGeneroLit = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        DTD_Autores = new javax.swing.JMenuItem();
        XSD_Autores = new javax.swing.JMenuItem();
        DTD_Obras = new javax.swing.JMenuItem();
        XSD_Obras = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem15 = new javax.swing.JMenuItem();

        javax.swing.GroupLayout WarningsLayout = new javax.swing.GroupLayout(Warnings.getContentPane());
        Warnings.getContentPane().setLayout(WarningsLayout);
        WarningsLayout.setHorizontalGroup(
            WarningsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        WarningsLayout.setVerticalGroup(
            WarningsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        ADN_TF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADN_TF1ActionPerformed(evt);
            }
        });

        ADN_B.setText("Alterar");
        ADN_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADN_BActionPerformed(evt);
            }
        });

        ADN_Label1.setText("Nome do Autor");

        ADN_Lebal2.setText("Nova data de nascimento:");

        javax.swing.GroupLayout ADNLayout = new javax.swing.GroupLayout(ADN.getContentPane());
        ADN.getContentPane().setLayout(ADNLayout);
        ADNLayout.setHorizontalGroup(
            ADNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ADNLayout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addGroup(ADNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ADN_B)
                    .addComponent(ADN_Label1)
                    .addComponent(ADN_Lebal2)
                    .addComponent(ADN_TF1)
                    .addComponent(ADN_TF2, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        ADNLayout.setVerticalGroup(
            ADNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ADNLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(ADN_Label1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ADN_TF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(ADN_Lebal2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ADN_TF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(ADN_B)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        ANC_TF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ANC_TF1ActionPerformed(evt);
            }
        });

        ANC_B1.setText("Alterar");
        ANC_B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ANC_B1ActionPerformed(evt);
            }
        });

        ANC_Label1.setText("Nome do Autor");

        ANC_Label2.setText("Nova nacionalidade");

        javax.swing.GroupLayout ANCLayout = new javax.swing.GroupLayout(ANC.getContentPane());
        ANC.getContentPane().setLayout(ANCLayout);
        ANCLayout.setHorizontalGroup(
            ANCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ANCLayout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addGroup(ANCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ANC_B1)
                    .addComponent(ANC_Label1)
                    .addComponent(ANC_Label2)
                    .addComponent(ANC_TF1)
                    .addComponent(ANC_TF2, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        ANCLayout.setVerticalGroup(
            ANCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ANCLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(ANC_Label1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ANC_TF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(ANC_Label2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ANC_TF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(ANC_B1)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        ACJ_TF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACJ_TF1ActionPerformed(evt);
            }
        });

        ACJ_B1.setText("Alterar");
        ACJ_B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACJ_B1ActionPerformed(evt);
            }
        });

        ACJ_L1.setText("Nome do Autor");

        ACJ_L2.setText("Novo/a conjuge");

        javax.swing.GroupLayout ACJLayout = new javax.swing.GroupLayout(ACJ.getContentPane());
        ACJ.getContentPane().setLayout(ACJLayout);
        ACJLayout.setHorizontalGroup(
            ACJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ACJLayout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addGroup(ACJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ACJ_B1)
                    .addComponent(ACJ_L1)
                    .addComponent(ACJ_L2)
                    .addComponent(ACJ_TF1)
                    .addComponent(ACJ_TF2, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        ACJLayout.setVerticalGroup(
            ACJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ACJLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(ACJ_L1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ACJ_TF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(ACJ_L2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ACJ_TF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(ACJ_B1)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        AGL_TF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AGL_TF1ActionPerformed(evt);
            }
        });

        AGL_B1.setText("Alterar");
        AGL_B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AGL_B1ActionPerformed(evt);
            }
        });

        AGL_L1.setText("Nome do Autor");

        AGL_L2.setText("Novo genero literario");

        javax.swing.GroupLayout AGLLayout = new javax.swing.GroupLayout(AGL.getContentPane());
        AGL.getContentPane().setLayout(AGLLayout);
        AGLLayout.setHorizontalGroup(
            AGLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AGLLayout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addGroup(AGLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AGL_B1)
                    .addComponent(AGL_L1)
                    .addComponent(AGL_L2)
                    .addComponent(AGL_TF1)
                    .addComponent(AGL_TF2, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        AGLLayout.setVerticalGroup(
            AGLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AGLLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(AGL_L1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AGL_TF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(AGL_L2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AGL_TF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(AGL_B1)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setText("Outputs");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Inserir o nome do autor:");

        ButtonAdd.setText("Adicionar");
        ButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAddActionPerformed(evt);
            }
        });

        ButtonEliminar.setText("Eliminar");
        ButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEliminarActionPerformed(evt);
            }
        });

        jLabel2.setText("Insira o numero de obras: (5 a 1)");

        Inicio.setText("Inicio");
        Inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InicioActionPerformed(evt);
            }
        });

        Relatorio.setText("Relatorio");
        Relatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelatorioActionPerformed(evt);
            }
        });
        Inicio.add(Relatorio);

        Autores.setText("Autores");
        Autores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AutoresActionPerformed(evt);
            }
        });
        Inicio.add(Autores);

        Sair.setText("Sair");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });
        Inicio.add(Sair);

        jMenuBar1.add(Inicio);

        Menu_XML.setText("XML");
        Menu_XML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_XMLActionPerformed(evt);
            }
        });

        Autores_XML.setText("Autores.XML");
        Autores_XML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Autores_XMLActionPerformed(evt);
            }
        });
        Menu_XML.add(Autores_XML);

        Obras_XML.setText("Obras.XML");
        Obras_XML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Obras_XMLActionPerformed(evt);
            }
        });
        Menu_XML.add(Obras_XML);

        EliminarAutor.setText("Eliminar autor");
        Menu_XML.add(EliminarAutor);

        AlterarDataNasc.setText("Alterar data de nascimento");
        AlterarDataNasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterarDataNascActionPerformed(evt);
            }
        });
        Menu_XML.add(AlterarDataNasc);

        AlterarNacionalidade.setText("Alterar nacionalidade");
        AlterarNacionalidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterarNacionalidadeActionPerformed(evt);
            }
        });
        Menu_XML.add(AlterarNacionalidade);

        jMenuItem8.setText("Acrescentar prêmio");
        Menu_XML.add(jMenuItem8);

        jMenuItem9.setText("Eliminar prêmio");
        Menu_XML.add(jMenuItem9);

        AlterarConjuge.setText("Alterar conjuge");
        AlterarConjuge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterarConjugeActionPerformed(evt);
            }
        });
        Menu_XML.add(AlterarConjuge);

        AlterarGeneroLit.setText("Alterar genero literario");
        AlterarGeneroLit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterarGeneroLitActionPerformed(evt);
            }
        });
        Menu_XML.add(AlterarGeneroLit);

        jMenuBar1.add(Menu_XML);

        jMenu3.setText("XPath");

        jMenuItem16.setText("Pesquisar informações autor");
        jMenu3.add(jMenuItem16);

        jMenuItem17.setText("Pesquisar autor por país/nacionalidade");
        jMenu3.add(jMenuItem17);

        jMenuItem18.setText("Pesquisar obras do autor");
        jMenu3.add(jMenuItem18);

        jMenuItem19.setText("Pesquisar autor mais premiado");
        jMenu3.add(jMenuItem19);

        jMenuItem20.setText("Pesquisar livros editados por preco (>...)");
        jMenu3.add(jMenuItem20);

        jMenuItem21.setText("Pesquisar autor pelo genero literario");
        jMenu3.add(jMenuItem21);

        jMenuItem22.setText("Pesquisar conjuge do autor/autora");
        jMenu3.add(jMenuItem22);

        jMenuItem23.setText("Pesquisar por data de nascimento");
        jMenu3.add(jMenuItem23);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Validar");

        DTD_Autores.setText("DTD_Autores");
        DTD_Autores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DTD_AutoresActionPerformed(evt);
            }
        });
        jMenu4.add(DTD_Autores);

        XSD_Autores.setText("XSD_Autores");
        XSD_Autores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XSD_AutoresActionPerformed(evt);
            }
        });
        jMenu4.add(XSD_Autores);

        DTD_Obras.setText("DTD_Obras");
        DTD_Obras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DTD_ObrasActionPerformed(evt);
            }
        });
        jMenu4.add(DTD_Obras);

        XSD_Obras.setText("XSD_Obras");
        XSD_Obras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XSD_ObrasActionPerformed(evt);
            }
        });
        jMenu4.add(XSD_Obras);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("XSLT");
        jMenuBar1.add(jMenu5);

        jMenu6.setText("XQuery");
        jMenuBar1.add(jMenu6);

        jMenu7.setText("Ajuda");

        jMenuItem15.setText("Exemplos de autores");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem15);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3)
                        .addComponent(jTextField1)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(ButtonAdd)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(ButtonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jTextField2))
                    .addComponent(jLabel2))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(5, 5, 5)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(5, 5, 5)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ButtonAdd)
                            .addComponent(ButtonEliminar)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RelatorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RelatorioActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        try {
            String textoAux = FuncAuxs.lerFicheiro("escritores.txt");
            jTextArea1.setText(textoAux);

        } catch (IOException ex) {
            Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void InicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InicioActionPerformed

    }//GEN-LAST:event_InicioActionPerformed

    private void AutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AutoresActionPerformed

        String nomeAux = ("Micael Eid - 2019112744"
                + "\nBruno Oliveira - 2019136478");
        jTextArea1.setText(nomeAux);


    }//GEN-LAST:event_AutoresActionPerformed

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SairActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void ButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAddActionPerformed
        try {

            String nome = jTextField1.getText();
            String quant = jTextField2.getText();

            if ("".equals(nome)) {
                Warnings.setVisible(false);
                JOptionPane.showMessageDialog(this,
                        "Insira um nome!",
                        "Aviso",
                        JOptionPane.INFORMATION_MESSAGE);
            } else {

                Autor au = WrappersWikipedia.criaAutor(nome);

                Document doc = XMLJDomFunctions.lerDocumentoXML("autores.xml");
                
                
                if(AchaNome(nome, doc)){
                    Warnings.setVisible(false);
                    JOptionPane.showMessageDialog(this,
                        "Autor ja existe",
                        "Informação",
                        JOptionPane.INFORMATION_MESSAGE);
                    
                    return;
                }
                
                doc = ModeloXML.adicionaAutor(au, doc);

                XMLJDomFunctions.escreverDocumentoParaFicheiro(doc, "autores.xml");

                Warnings.setVisible(false);
                JOptionPane.showMessageDialog(this,
                        "Autor adicionado com sucesso",
                        "Informação",
                        JOptionPane.INFORMATION_MESSAGE);

                if (!"".equals(quant)) {
                    ArrayList<Obras> obs = new ArrayList<>();
                    ArrayList<String> linkObras = WrappersBertrand.obtem_link(nome, Integer.parseInt(quant));

                    for (int i = 0; i < linkObras.size(); i++) {
                        obs.add(WrappersBertrand.criaObras(linkObras.get(i)));
                    }

                    Document doc2 = XMLJDomFunctions.lerDocumentoXML("obras.xml");

                    doc2 = ModeloXML.adicionaObra(obs, doc2);

                    XMLJDomFunctions.escreverDocumentoParaFicheiro(doc2, "obras.xml");

                    Warnings.setVisible(false);
                    JOptionPane.showMessageDialog(this,
                            "Obra/as adicionada/as com sucesso",
                            "Informação",
                            JOptionPane.INFORMATION_MESSAGE);

                }

            }

            //jDialog1.setVisible(false);
        } catch (IOException ex) {
            Warnings.setVisible(false);
            JOptionPane.showMessageDialog(this,
                    "Erro ao Adicionar um autor",
                    "Aviso",
                    JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);

        }
    }//GEN-LAST:event_ButtonAddActionPerformed

    private void Menu_XMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_XMLActionPerformed

    }//GEN-LAST:event_Menu_XMLActionPerformed

    private void Obras_XMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Obras_XMLActionPerformed
        Document doc = XMLJDomFunctions.lerDocumentoXML("obras.xml");
        String texto = XMLJDomFunctions.escreverDocumentoString(doc);

        jTextArea1.setText(texto);
    }//GEN-LAST:event_Obras_XMLActionPerformed

    private void Autores_XMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Autores_XMLActionPerformed
        Document doc = XMLJDomFunctions.lerDocumentoXML("autores.xml");
        String texto = XMLJDomFunctions.escreverDocumentoString(doc);

        jTextArea1.setText(texto);
    }//GEN-LAST:event_Autores_XMLActionPerformed

    private void ButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEliminarActionPerformed
        String nome = jTextField1.getText();

        if ("".equals(nome)) {
            Warnings.setVisible(false);
            JOptionPane.showMessageDialog(this,
                    "Insira um nome!",
                    "Aviso",
                    JOptionPane.INFORMATION_MESSAGE);
        } else {
            Document doc = XMLJDomFunctions.lerDocumentoXML("autores.xml");

            if (doc == null) {

                Warnings.setVisible(false);
                JOptionPane.showMessageDialog(this,
                        "Ficheiro nao encontrado",
                        "Aviso",
                        JOptionPane.ERROR_MESSAGE);

            } else if (doc != null) {
                doc = ModeloXML.removeAutorNome(nome, doc);
                XMLJDomFunctions.escreverDocumentoParaFicheiro(doc, "autores.xml");

                Warnings.setVisible(false);
                JOptionPane.showMessageDialog(this,
                        "Autor removido com sucesso",
                        "Informação",
                        JOptionPane.INFORMATION_MESSAGE);
            } else {
                Warnings.setVisible(false);
                JOptionPane.showMessageDialog(this,
                        "Nome invalido",
                        "Aviso",
                        JOptionPane.ERROR_MESSAGE);
            }
        }


    }//GEN-LAST:event_ButtonEliminarActionPerformed

    private void DTD_AutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DTD_AutoresActionPerformed
        try {
            // TODO add your handling code here:
            int res = Validacao.validarDocumentoDTD("autores.xml", "autores.dtd");
            if (res == 1) {
                JOptionPane.showMessageDialog(this,
                        "Ficheiro válido por DTD",
                        "Validação DTD",
                        JOptionPane.INFORMATION_MESSAGE);
            }
            if (res == -1) {
                JOptionPane.showMessageDialog(this,
                        "Ficheiro inválido por DTD",
                        "Validação DTD",
                        JOptionPane.ERROR_MESSAGE);
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this,
                    "Verifique se os ficheiros XML e DTD existem",
                    "Validação DTD",
                    JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_DTD_AutoresActionPerformed

    private void XSD_AutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XSD_AutoresActionPerformed
        // TODO add your handling code here:
           int res = Validacao.validarDocumentoXSD("autores.xml", "autores.xsd");
        if (res == -1) {
            
             Warnings.setVisible(false);
                JOptionPane.showMessageDialog(this,
                        "O Ficheiro e valido",
                        "Validacao XSD",
                        JOptionPane.INFORMATION_MESSAGE);
        } else {
            
            Warnings.setVisible(false);
                JOptionPane.showMessageDialog(this,
                        "O Ficheiro e invalido",
                        "Validacao XSD",
                        JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_XSD_AutoresActionPerformed

    private void DTD_ObrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DTD_ObrasActionPerformed
         try {
            // TODO add your handling code here:
            int res = Validacao.validarDocumentoDTD("obras.xml", "obras.dtd");
            if (res == 1) {
                JOptionPane.showMessageDialog(this,
                        "Ficheiro válido por DTD",
                        "Validação DTD",
                        JOptionPane.INFORMATION_MESSAGE);
            }
            if (res == -1) {
                JOptionPane.showMessageDialog(this,
                        "Ficheiro inválido por DTD",
                        "Validação DTD",
                        JOptionPane.ERROR_MESSAGE);
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this,
                    "Verifique se os ficheiros XML e DTD existem",
                    "Validação DTD",
                    JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_DTD_ObrasActionPerformed

    private void XSD_ObrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XSD_ObrasActionPerformed
          int res = Validacao.validarDocumentoXSD("obras.xml", "obras.xsd");
        if (res == -1) {
            
             Warnings.setVisible(false);
                JOptionPane.showMessageDialog(this,
                        "O Ficheiro e valido",
                        "Validacao XSD",
                        JOptionPane.INFORMATION_MESSAGE);
        } else {
            
            Warnings.setVisible(false);
                JOptionPane.showMessageDialog(this,
                        "O Ficheiro e invalido",
                        "Validacao XSD",
                        JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_XSD_ObrasActionPerformed

    private void AlterarDataNascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterarDataNascActionPerformed
        // TODO add your handling code here:
        ADN.setSize(450, 300);
        ADN.setLocation(500, 300);
        ADN.setTitle("Alterar Data Nascimento");
        ADN.setVisible(true);
    }//GEN-LAST:event_AlterarDataNascActionPerformed

    private void ADN_TF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADN_TF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADN_TF1ActionPerformed

    private void ADN_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADN_BActionPerformed
        Document doc = XMLJDomFunctions.lerDocumentoXML("autores.xml");
        
        doc = ModeloXML.alterarDataNasc(ADN_TF1.getText(), ADN_TF2.getText(), doc);
        
        JOptionPane.showMessageDialog(this,
                "Data alterada com sucesso",
                "Informação",
                JOptionPane.INFORMATION_MESSAGE);
        
        //grava o ficheiro XML em disco
        if (doc != null) {
            XMLJDomFunctions.escreverDocumentoParaFicheiro(doc, "autores.xml");
        } else {
            JOptionPane.showMessageDialog(this,
                    "Autor não foi encontrado",
                    "Informação",
                    JOptionPane.INFORMATION_MESSAGE);
        }
        ADN.setVisible(false);
    }//GEN-LAST:event_ADN_BActionPerformed

    private void ANC_TF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ANC_TF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ANC_TF1ActionPerformed

    private void ANC_B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ANC_B1ActionPerformed
        Document doc = XMLJDomFunctions.lerDocumentoXML("autores.xml");
        
        doc = ModeloXML.alterarNacionalidade(ANC_TF1.getText(), ANC_TF2.getText(), doc);
        
        JOptionPane.showMessageDialog(this,
                "Nacionalidade alterada com sucesso",
                "Informação",
                JOptionPane.INFORMATION_MESSAGE);
        
        //grava o ficheiro XML em disco
        if (doc != null) {
            XMLJDomFunctions.escreverDocumentoParaFicheiro(doc, "autores.xml");
        } else {
            JOptionPane.showMessageDialog(this,
                    "Autor não foi encontrado",
                    "Informação",
                    JOptionPane.INFORMATION_MESSAGE);
        }
        ANC.setVisible(false);
    }//GEN-LAST:event_ANC_B1ActionPerformed

    private void AlterarNacionalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterarNacionalidadeActionPerformed
        ANC.setSize(450, 300);
        ANC.setLocation(500, 300);
        ANC.setTitle("Alterar Nacionalidade");
        ANC.setVisible(true);
    }//GEN-LAST:event_AlterarNacionalidadeActionPerformed

    private void ACJ_TF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACJ_TF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ACJ_TF1ActionPerformed

    private void ACJ_B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACJ_B1ActionPerformed
        Document doc = XMLJDomFunctions.lerDocumentoXML("autores.xml");
        
        doc = ModeloXML.alterarConjuge(ACJ_TF1.getText(), ACJ_TF2.getText(), doc);
        
        JOptionPane.showMessageDialog(this,
                "Conjuge alterado com sucesso",
                "Informação",
                JOptionPane.INFORMATION_MESSAGE);
        
        //grava o ficheiro XML em disco
        if (doc != null) {
            XMLJDomFunctions.escreverDocumentoParaFicheiro(doc, "autores.xml");
        } else {
            JOptionPane.showMessageDialog(this,
                    "Autor não foi encontrado",
                    "Informação",
                    JOptionPane.INFORMATION_MESSAGE);
        }
        ACJ.setVisible(false);
    }//GEN-LAST:event_ACJ_B1ActionPerformed

    private void AlterarConjugeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterarConjugeActionPerformed
        ACJ.setSize(450, 300);
        ACJ.setLocation(500, 300);
        ACJ.setTitle("Alterar Conjuge");
        ACJ.setVisible(true);
    }//GEN-LAST:event_AlterarConjugeActionPerformed

    private void AGL_TF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AGL_TF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AGL_TF1ActionPerformed

    private void AGL_B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AGL_B1ActionPerformed
        Document doc = XMLJDomFunctions.lerDocumentoXML("autores.xml");
        
        doc = ModeloXML.alterarGeneroLit(AGL_TF1.getText(), AGL_TF2.getText(), doc);
        
        JOptionPane.showMessageDialog(this,
                "Genero Literario alterado com sucesso",
                "Informação",
                JOptionPane.INFORMATION_MESSAGE);
        
        //grava o ficheiro XML em disco
        if (doc != null) {
            XMLJDomFunctions.escreverDocumentoParaFicheiro(doc, "autores.xml");
        } else {
            JOptionPane.showMessageDialog(this,
                    "Autor não foi encontrado",
                    "Informação",
                    JOptionPane.INFORMATION_MESSAGE);
        }
        AGL.setVisible(false);
    }//GEN-LAST:event_AGL_B1ActionPerformed

    private void AlterarGeneroLitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterarGeneroLitActionPerformed
        AGL.setSize(450, 300);
        AGL.setLocation(500, 300);
        AGL.setTitle("Alterar Genero Literario");
        AGL.setVisible(true);
    }//GEN-LAST:event_AlterarGeneroLitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog ACJ;
    private javax.swing.JButton ACJ_B1;
    private javax.swing.JLabel ACJ_L1;
    private javax.swing.JLabel ACJ_L2;
    private javax.swing.JTextField ACJ_TF1;
    private javax.swing.JTextField ACJ_TF2;
    private javax.swing.JDialog ADN;
    private javax.swing.JButton ADN_B;
    private javax.swing.JLabel ADN_Label1;
    private javax.swing.JLabel ADN_Lebal2;
    private javax.swing.JTextField ADN_TF1;
    private javax.swing.JTextField ADN_TF2;
    private javax.swing.JDialog AGL;
    private javax.swing.JButton AGL_B1;
    private javax.swing.JLabel AGL_L1;
    private javax.swing.JLabel AGL_L2;
    private javax.swing.JTextField AGL_TF1;
    private javax.swing.JTextField AGL_TF2;
    private javax.swing.JDialog ANC;
    private javax.swing.JButton ANC_B1;
    private javax.swing.JLabel ANC_Label1;
    private javax.swing.JLabel ANC_Label2;
    private javax.swing.JTextField ANC_TF1;
    private javax.swing.JTextField ANC_TF2;
    private javax.swing.JMenuItem AlterarConjuge;
    private javax.swing.JMenuItem AlterarDataNasc;
    private javax.swing.JMenuItem AlterarGeneroLit;
    private javax.swing.JMenuItem AlterarNacionalidade;
    private javax.swing.JMenuItem Autores;
    private javax.swing.JMenuItem Autores_XML;
    private javax.swing.JButton ButtonAdd;
    private javax.swing.JButton ButtonEliminar;
    private javax.swing.JMenuItem DTD_Autores;
    private javax.swing.JMenuItem DTD_Obras;
    private javax.swing.JMenuItem EliminarAutor;
    private javax.swing.JMenu Inicio;
    private javax.swing.JMenu Menu_XML;
    private javax.swing.JMenuItem Obras_XML;
    private javax.swing.JMenuItem Relatorio;
    private javax.swing.JMenuItem Sair;
    private javax.swing.JDialog Warnings;
    private javax.swing.JMenuItem XSD_Autores;
    private javax.swing.JMenuItem XSD_Obras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
