/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package id_tp.tp_id_22_23;

import java.awt.Frame;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.saxon.s9api.SaxonApiException;
import net.sf.saxon.s9api.XdmValue;
import org.jdom2.Document;
import org.jdom2.Element;

/**
 *
 * @author mikae
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
    }

    public static boolean AchaNome(String nomeAutor, Document doc) {
        Element raiz;
        raiz = doc.getRootElement();
        List todosAutores = raiz.getChildren("autor");
        boolean found = false;
        for (int i = 0; i < todosAutores.size(); i++) {
            Element autor = (Element) todosAutores.get(i); //obtem livro i da Lista 
            if (autor.getChild("nome").getText().contains(nomeAutor)) {
                found = true;
            }
        }
        if (!found) {
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Warnings = new javax.swing.JDialog();
        ADO = new javax.swing.JDialog();
        ADO_B1 = new javax.swing.JButton();
        ADO_L1 = new javax.swing.JLabel();
        ADO_L2 = new javax.swing.JLabel();
        ADO_TF1 = new javax.swing.JTextField();
        ADN = new javax.swing.JDialog();
        ADN_TF1 = new javax.swing.JTextField();
        ADN_TF2 = new javax.swing.JTextField();
        ADN_B = new javax.swing.JButton();
        ADN_Label1 = new javax.swing.JLabel();
        ADN_Lebal2 = new javax.swing.JLabel();
        ANC = new javax.swing.JDialog();
        ANC_TF1 = new javax.swing.JTextField();
        ANC_TF2 = new javax.swing.JTextField();
        ANC_B1 = new javax.swing.JButton();
        ANC_Label1 = new javax.swing.JLabel();
        ANC_Label2 = new javax.swing.JLabel();
        ACJ = new javax.swing.JDialog();
        ACJ_TF1 = new javax.swing.JTextField();
        ACJ_TF2 = new javax.swing.JTextField();
        ACJ_B1 = new javax.swing.JButton();
        ACJ_L1 = new javax.swing.JLabel();
        ACJ_L2 = new javax.swing.JLabel();
        AGL = new javax.swing.JDialog();
        AGL_TF1 = new javax.swing.JTextField();
        AGL_TF2 = new javax.swing.JTextField();
        AGL_B1 = new javax.swing.JButton();
        AGL_L1 = new javax.swing.JLabel();
        AGL_L2 = new javax.swing.JLabel();
        ACP = new javax.swing.JDialog();
        ACP_TF1 = new javax.swing.JTextField();
        ACP_TF2 = new javax.swing.JTextField();
        ACP_B1 = new javax.swing.JButton();
        ACP_L1 = new javax.swing.JLabel();
        ACP_L2 = new javax.swing.JLabel();
        RMP = new javax.swing.JDialog();
        RMP_TF1 = new javax.swing.JTextField();
        RMP_TF2 = new javax.swing.JTextField();
        RMP_B1 = new javax.swing.JButton();
        RMP_L1 = new javax.swing.JLabel();
        RMP_L2 = new javax.swing.JLabel();
        RMO = new javax.swing.JDialog();
        RMO_B1 = new javax.swing.JButton();
        RMO_L1 = new javax.swing.JLabel();
        RMO_TF1 = new javax.swing.JTextField();
        PIA = new javax.swing.JDialog();
        PIA_TF1 = new javax.swing.JTextField();
        PIA_B1 = new javax.swing.JButton();
        PIA_L1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        PIA_TA1 = new javax.swing.JTextArea();
        PIN = new javax.swing.JDialog();
        PIN_TF1 = new javax.swing.JTextField();
        PIN_B1 = new javax.swing.JButton();
        PIN_L1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        PIN_TA1 = new javax.swing.JTextArea();
        POA = new javax.swing.JDialog();
        POA_TF1 = new javax.swing.JTextField();
        POA_B1 = new javax.swing.JButton();
        POA_L1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        POA_TA1 = new javax.swing.JTextArea();
        PAP = new javax.swing.JDialog();
        PAP_B1 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        PAP_TA1 = new javax.swing.JTextArea();
        PPL = new javax.swing.JDialog();
        PPL_TF1 = new javax.swing.JTextField();
        PPL_B1 = new javax.swing.JButton();
        PPL_L1 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        PPL_TA1 = new javax.swing.JTextArea();
        PGL = new javax.swing.JDialog();
        PGL_TF1 = new javax.swing.JTextField();
        PGL_B1 = new javax.swing.JButton();
        PGL_L1 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        PGL_TA1 = new javax.swing.JTextArea();
        PPC = new javax.swing.JDialog();
        PPC_TF1 = new javax.swing.JTextField();
        PPC_B1 = new javax.swing.JButton();
        PPC_L1 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        PPC_TA1 = new javax.swing.JTextArea();
        PDN = new javax.swing.JDialog();
        PDN_TF1 = new javax.swing.JTextField();
        PDN_B1 = new javax.swing.JButton();
        PDN_L1 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        PDN_TA1 = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ButtonAdd = new javax.swing.JButton();
        ButtonEliminar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        Inicio = new javax.swing.JMenu();
        Relatorio = new javax.swing.JMenuItem();
        Autores = new javax.swing.JMenuItem();
        Sair = new javax.swing.JMenuItem();
        Menu_XML = new javax.swing.JMenu();
        Autores_XML = new javax.swing.JMenuItem();
        Obras_XML = new javax.swing.JMenuItem();
        AlterarDataNasc = new javax.swing.JMenuItem();
        AlterarNacionalidade = new javax.swing.JMenuItem();
        AcrescentarPremio = new javax.swing.JMenuItem();
        EliminaPremio = new javax.swing.JMenuItem();
        AlterarConjuge = new javax.swing.JMenuItem();
        AlterarGeneroLit = new javax.swing.JMenuItem();
        EliminarObra = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        P_InfoAutor = new javax.swing.JMenuItem();
        P_autorNacionalidade = new javax.swing.JMenuItem();
        P_ObrasAutor = new javax.swing.JMenuItem();
        P_AutorPremiado = new javax.swing.JMenuItem();
        P_LivrosPreco = new javax.swing.JMenuItem();
        P_AutorGenero = new javax.swing.JMenuItem();
        P_ConjugeAutor = new javax.swing.JMenuItem();
        P_AutorDataNasc = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        DTD_Autores = new javax.swing.JMenuItem();
        XSD_Autores = new javax.swing.JMenuItem();
        DTD_Obras = new javax.swing.JMenuItem();
        XSD_Obras = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem15 = new javax.swing.JMenuItem();

        javax.swing.GroupLayout WarningsLayout = new javax.swing.GroupLayout(Warnings.getContentPane());
        Warnings.getContentPane().setLayout(WarningsLayout);
        WarningsLayout.setHorizontalGroup(
            WarningsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        WarningsLayout.setVerticalGroup(
            WarningsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        ADO_B1.setText("Adicionar");
        ADO_B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADO_B1ActionPerformed(evt);
            }
        });

        ADO_L1.setText("Quantas obras você deseja adicionar?");

        ADO_L2.setText("Entre 1 e 5");

        ADO_TF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADO_TF1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ADOLayout = new javax.swing.GroupLayout(ADO.getContentPane());
        ADO.getContentPane().setLayout(ADOLayout);
        ADOLayout.setHorizontalGroup(
            ADOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ADOLayout.createSequentialGroup()
                .addGroup(ADOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ADOLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(ADOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ADO_L1)
                            .addGroup(ADOLayout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(ADO_L2))))
                    .addGroup(ADOLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(ADOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ADO_TF1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ADOLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(ADO_B1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        ADOLayout.setVerticalGroup(
            ADOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ADOLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(ADO_L1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ADO_L2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ADO_TF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ADO_B1)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        ADN_TF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADN_TF1ActionPerformed(evt);
            }
        });

        ADN_B.setText("Alterar");
        ADN_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADN_BActionPerformed(evt);
            }
        });

        ADN_Label1.setText("Nome do Autor");

        ADN_Lebal2.setText("Nova data de nascimento:");

        javax.swing.GroupLayout ADNLayout = new javax.swing.GroupLayout(ADN.getContentPane());
        ADN.getContentPane().setLayout(ADNLayout);
        ADNLayout.setHorizontalGroup(
            ADNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ADNLayout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addGroup(ADNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ADN_B)
                    .addComponent(ADN_Label1)
                    .addComponent(ADN_Lebal2)
                    .addComponent(ADN_TF1)
                    .addComponent(ADN_TF2, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        ADNLayout.setVerticalGroup(
            ADNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ADNLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(ADN_Label1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ADN_TF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(ADN_Lebal2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ADN_TF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(ADN_B)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        ANC_TF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ANC_TF1ActionPerformed(evt);
            }
        });

        ANC_B1.setText("Alterar");
        ANC_B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ANC_B1ActionPerformed(evt);
            }
        });

        ANC_Label1.setText("Nome do Autor");

        ANC_Label2.setText("Nova nacionalidade");

        javax.swing.GroupLayout ANCLayout = new javax.swing.GroupLayout(ANC.getContentPane());
        ANC.getContentPane().setLayout(ANCLayout);
        ANCLayout.setHorizontalGroup(
            ANCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ANCLayout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addGroup(ANCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ANC_B1)
                    .addComponent(ANC_Label1)
                    .addComponent(ANC_Label2)
                    .addComponent(ANC_TF1)
                    .addComponent(ANC_TF2, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        ANCLayout.setVerticalGroup(
            ANCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ANCLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(ANC_Label1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ANC_TF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(ANC_Label2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ANC_TF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(ANC_B1)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        ACJ_TF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACJ_TF1ActionPerformed(evt);
            }
        });

        ACJ_B1.setText("Alterar");
        ACJ_B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACJ_B1ActionPerformed(evt);
            }
        });

        ACJ_L1.setText("Nome do Autor");

        ACJ_L2.setText("Novo/a conjuge");

        javax.swing.GroupLayout ACJLayout = new javax.swing.GroupLayout(ACJ.getContentPane());
        ACJ.getContentPane().setLayout(ACJLayout);
        ACJLayout.setHorizontalGroup(
            ACJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ACJLayout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addGroup(ACJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ACJ_B1)
                    .addComponent(ACJ_L1)
                    .addComponent(ACJ_L2)
                    .addComponent(ACJ_TF1)
                    .addComponent(ACJ_TF2, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        ACJLayout.setVerticalGroup(
            ACJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ACJLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(ACJ_L1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ACJ_TF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(ACJ_L2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ACJ_TF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(ACJ_B1)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        AGL_TF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AGL_TF1ActionPerformed(evt);
            }
        });

        AGL_B1.setText("Alterar");
        AGL_B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AGL_B1ActionPerformed(evt);
            }
        });

        AGL_L1.setText("Nome do Autor");

        AGL_L2.setText("Novo genero literario");

        javax.swing.GroupLayout AGLLayout = new javax.swing.GroupLayout(AGL.getContentPane());
        AGL.getContentPane().setLayout(AGLLayout);
        AGLLayout.setHorizontalGroup(
            AGLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AGLLayout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addGroup(AGLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AGL_B1)
                    .addComponent(AGL_L1)
                    .addComponent(AGL_L2)
                    .addComponent(AGL_TF1)
                    .addComponent(AGL_TF2, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        AGLLayout.setVerticalGroup(
            AGLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AGLLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(AGL_L1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AGL_TF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(AGL_L2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AGL_TF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(AGL_B1)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        ACP_TF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACP_TF1ActionPerformed(evt);
            }
        });

        ACP_B1.setText("Adicionar");
        ACP_B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACP_B1ActionPerformed(evt);
            }
        });

        ACP_L1.setText("Nome do Autor");

        ACP_L2.setText("Novo premio");

        javax.swing.GroupLayout ACPLayout = new javax.swing.GroupLayout(ACP.getContentPane());
        ACP.getContentPane().setLayout(ACPLayout);
        ACPLayout.setHorizontalGroup(
            ACPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ACPLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(ACPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ACP_B1)
                    .addComponent(ACP_L1)
                    .addComponent(ACP_TF1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ACP_L2)
                    .addComponent(ACP_TF2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        ACPLayout.setVerticalGroup(
            ACPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ACPLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(ACP_L1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ACP_TF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ACP_L2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ACP_TF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(ACP_B1)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        RMP_TF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RMP_TF1ActionPerformed(evt);
            }
        });

        RMP_B1.setText("Remover");
        RMP_B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RMP_B1ActionPerformed(evt);
            }
        });

        RMP_L1.setText("Nome do Autor");

        RMP_L2.setText("Nome do premio");

        javax.swing.GroupLayout RMPLayout = new javax.swing.GroupLayout(RMP.getContentPane());
        RMP.getContentPane().setLayout(RMPLayout);
        RMPLayout.setHorizontalGroup(
            RMPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RMPLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(RMPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RMP_B1)
                    .addComponent(RMP_L1)
                    .addComponent(RMP_TF1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RMP_L2)
                    .addComponent(RMP_TF2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        RMPLayout.setVerticalGroup(
            RMPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RMPLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(RMP_L1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RMP_TF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RMP_L2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RMP_TF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(RMP_B1)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        RMO_B1.setText("Eliminar");
        RMO_B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RMO_B1ActionPerformed(evt);
            }
        });

        RMO_L1.setText("Nome da obra:");

        RMO_TF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RMO_TF1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RMOLayout = new javax.swing.GroupLayout(RMO.getContentPane());
        RMO.getContentPane().setLayout(RMOLayout);
        RMOLayout.setHorizontalGroup(
            RMOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RMOLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(RMOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RMO_B1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RMO_L1)
                    .addComponent(RMO_TF1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        RMOLayout.setVerticalGroup(
            RMOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RMOLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(RMO_L1)
                .addGap(18, 18, 18)
                .addComponent(RMO_TF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RMO_B1)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        PIA_TF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PIA_TF1ActionPerformed(evt);
            }
        });

        PIA_B1.setText("Pesquisar");
        PIA_B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PIA_B1ActionPerformed(evt);
            }
        });

        PIA_L1.setText("Nome do Autor:");

        PIA_TA1.setColumns(20);
        PIA_TA1.setRows(5);
        jScrollPane2.setViewportView(PIA_TA1);

        javax.swing.GroupLayout PIALayout = new javax.swing.GroupLayout(PIA.getContentPane());
        PIA.getContentPane().setLayout(PIALayout);
        PIALayout.setHorizontalGroup(
            PIALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PIALayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(PIALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PIA_B1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PIA_TF1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PIA_L1))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        PIALayout.setVerticalGroup(
            PIALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PIALayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(PIA_L1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PIA_TF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(PIA_B1)
                .addGap(16, 16, 16))
        );

        PIN_TF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PIN_TF1ActionPerformed(evt);
            }
        });

        PIN_B1.setText("Pesquisar");
        PIN_B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PIN_B1ActionPerformed(evt);
            }
        });

        PIN_L1.setText("Nacionalidade do Autor/Autora");

        PIN_TA1.setColumns(20);
        PIN_TA1.setRows(5);
        jScrollPane3.setViewportView(PIN_TA1);

        javax.swing.GroupLayout PINLayout = new javax.swing.GroupLayout(PIN.getContentPane());
        PIN.getContentPane().setLayout(PINLayout);
        PINLayout.setHorizontalGroup(
            PINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PINLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(PINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PIN_B1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(PIN_TF1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(PIN_L1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        PINLayout.setVerticalGroup(
            PINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PINLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(PIN_L1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PIN_TF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(PIN_B1)
                .addGap(16, 16, 16))
        );

        POA_TF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                POA_TF1ActionPerformed(evt);
            }
        });

        POA_B1.setText("Pesquisar");
        POA_B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                POA_B1ActionPerformed(evt);
            }
        });

        POA_L1.setText("Nome do Autor/a");

        POA_TA1.setColumns(20);
        POA_TA1.setRows(5);
        jScrollPane4.setViewportView(POA_TA1);

        javax.swing.GroupLayout POALayout = new javax.swing.GroupLayout(POA.getContentPane());
        POA.getContentPane().setLayout(POALayout);
        POALayout.setHorizontalGroup(
            POALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(POALayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(POALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(POA_B1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(POALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(POA_L1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                        .addComponent(POA_TF1, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        POALayout.setVerticalGroup(
            POALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(POALayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(POA_L1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(POA_TF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(POA_B1)
                .addGap(16, 16, 16))
        );

        PAP_B1.setText("Pesquisar");
        PAP_B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PAP_B1ActionPerformed(evt);
            }
        });

        PAP_TA1.setColumns(20);
        PAP_TA1.setRows(5);
        jScrollPane5.setViewportView(PAP_TA1);

        javax.swing.GroupLayout PAPLayout = new javax.swing.GroupLayout(PAP.getContentPane());
        PAP.getContentPane().setLayout(PAPLayout);
        PAPLayout.setHorizontalGroup(
            PAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PAPLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(PAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PAPLayout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(PAP_B1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        PAPLayout.setVerticalGroup(
            PAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PAPLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(PAP_B1)
                .addGap(80, 80, 80))
        );

        PPL_TF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PPL_TF1ActionPerformed(evt);
            }
        });

        PPL_B1.setText("Pesquisar");
        PPL_B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PPL_B1ActionPerformed(evt);
            }
        });

        PPL_L1.setText("Preço do livro:");

        PPL_TA1.setColumns(20);
        PPL_TA1.setRows(5);
        jScrollPane7.setViewportView(PPL_TA1);

        javax.swing.GroupLayout PPLLayout = new javax.swing.GroupLayout(PPL.getContentPane());
        PPL.getContentPane().setLayout(PPLLayout);
        PPLLayout.setHorizontalGroup(
            PPLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PPLLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(PPLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PPL_B1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PPLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(PPL_L1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                        .addComponent(PPL_TF1, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        PPLLayout.setVerticalGroup(
            PPLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PPLLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(PPL_L1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PPL_TF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(PPL_B1)
                .addGap(16, 16, 16))
        );

        PGL_TF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PGL_TF1ActionPerformed(evt);
            }
        });

        PGL_B1.setText("Pesquisar");
        PGL_B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PGL_B1ActionPerformed(evt);
            }
        });

        PGL_L1.setText("Genero Literario:");

        PGL_TA1.setColumns(20);
        PGL_TA1.setRows(5);
        jScrollPane8.setViewportView(PGL_TA1);

        javax.swing.GroupLayout PGLLayout = new javax.swing.GroupLayout(PGL.getContentPane());
        PGL.getContentPane().setLayout(PGLLayout);
        PGLLayout.setHorizontalGroup(
            PGLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PGLLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(PGLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PGL_B1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PGLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(PGL_L1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                        .addComponent(PGL_TF1, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        PGLLayout.setVerticalGroup(
            PGLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PGLLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(PGL_L1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PGL_TF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(PGL_B1)
                .addGap(16, 16, 16))
        );

        PPC_TF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PPC_TF1ActionPerformed(evt);
            }
        });

        PPC_B1.setText("Pesquisar");
        PPC_B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PPC_B1ActionPerformed(evt);
            }
        });

        PPC_L1.setText("Nome do autor/a:");

        PPC_TA1.setColumns(20);
        PPC_TA1.setRows(5);
        jScrollPane9.setViewportView(PPC_TA1);

        javax.swing.GroupLayout PPCLayout = new javax.swing.GroupLayout(PPC.getContentPane());
        PPC.getContentPane().setLayout(PPCLayout);
        PPCLayout.setHorizontalGroup(
            PPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PPCLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(PPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PPC_B1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(PPC_L1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                        .addComponent(PPC_TF1, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        PPCLayout.setVerticalGroup(
            PPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PPCLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(PPC_L1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PPC_TF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(PPC_B1)
                .addGap(16, 16, 16))
        );

        PDN_TF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PDN_TF1ActionPerformed(evt);
            }
        });

        PDN_B1.setText("Pesquisar");
        PDN_B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PDN_B1ActionPerformed(evt);
            }
        });

        PDN_L1.setText("Data de Nascimento:");

        PDN_TA1.setColumns(20);
        PDN_TA1.setRows(5);
        jScrollPane10.setViewportView(PDN_TA1);

        javax.swing.GroupLayout PDNLayout = new javax.swing.GroupLayout(PDN.getContentPane());
        PDN.getContentPane().setLayout(PDNLayout);
        PDNLayout.setHorizontalGroup(
            PDNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PDNLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(PDNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PDN_B1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PDNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(PDN_L1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                        .addComponent(PDN_TF1, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        PDNLayout.setVerticalGroup(
            PDNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PDNLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(PDN_L1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PDN_TF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(PDN_B1)
                .addGap(16, 16, 16))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setText("Outputs");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Inserir o nome do autor:");

        ButtonAdd.setText("Adicionar");
        ButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAddActionPerformed(evt);
            }
        });

        ButtonEliminar.setText("Eliminar");
        ButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEliminarActionPerformed(evt);
            }
        });

        Inicio.setText("Inicio");
        Inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InicioActionPerformed(evt);
            }
        });

        Relatorio.setText("Relatorio");
        Relatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelatorioActionPerformed(evt);
            }
        });
        Inicio.add(Relatorio);

        Autores.setText("Autores");
        Autores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AutoresActionPerformed(evt);
            }
        });
        Inicio.add(Autores);

        Sair.setText("Sair");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });
        Inicio.add(Sair);

        jMenuBar1.add(Inicio);

        Menu_XML.setText("XML");
        Menu_XML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_XMLActionPerformed(evt);
            }
        });

        Autores_XML.setText("Autores.XML");
        Autores_XML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Autores_XMLActionPerformed(evt);
            }
        });
        Menu_XML.add(Autores_XML);

        Obras_XML.setText("Obras.XML");
        Obras_XML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Obras_XMLActionPerformed(evt);
            }
        });
        Menu_XML.add(Obras_XML);

        AlterarDataNasc.setText("Alterar data de nascimento");
        AlterarDataNasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterarDataNascActionPerformed(evt);
            }
        });
        Menu_XML.add(AlterarDataNasc);

        AlterarNacionalidade.setText("Alterar nacionalidade");
        AlterarNacionalidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterarNacionalidadeActionPerformed(evt);
            }
        });
        Menu_XML.add(AlterarNacionalidade);

        AcrescentarPremio.setText("Acrescentar prêmio");
        AcrescentarPremio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcrescentarPremioActionPerformed(evt);
            }
        });
        Menu_XML.add(AcrescentarPremio);

        EliminaPremio.setText("Eliminar prêmio");
        EliminaPremio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminaPremioActionPerformed(evt);
            }
        });
        Menu_XML.add(EliminaPremio);

        AlterarConjuge.setText("Alterar conjuge");
        AlterarConjuge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterarConjugeActionPerformed(evt);
            }
        });
        Menu_XML.add(AlterarConjuge);

        AlterarGeneroLit.setText("Alterar genero literario");
        AlterarGeneroLit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterarGeneroLitActionPerformed(evt);
            }
        });
        Menu_XML.add(AlterarGeneroLit);

        EliminarObra.setText("Eliminar Obra");
        EliminarObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarObraActionPerformed(evt);
            }
        });
        Menu_XML.add(EliminarObra);

        jMenuBar1.add(Menu_XML);

        jMenu3.setText("XPath");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        P_InfoAutor.setText("Pesquisar informações autor");
        P_InfoAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P_InfoAutorActionPerformed(evt);
            }
        });
        jMenu3.add(P_InfoAutor);

        P_autorNacionalidade.setText("Pesquisar autor por país/nacionalidade");
        P_autorNacionalidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P_autorNacionalidadeActionPerformed(evt);
            }
        });
        jMenu3.add(P_autorNacionalidade);

        P_ObrasAutor.setText("Pesquisar obras do autor");
        P_ObrasAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P_ObrasAutorActionPerformed(evt);
            }
        });
        jMenu3.add(P_ObrasAutor);

        P_AutorPremiado.setText("Pesquisar autor mais premiado");
        P_AutorPremiado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P_AutorPremiadoActionPerformed(evt);
            }
        });
        jMenu3.add(P_AutorPremiado);

        P_LivrosPreco.setText("Pesquisar livros editados por preco (>...)");
        P_LivrosPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P_LivrosPrecoActionPerformed(evt);
            }
        });
        jMenu3.add(P_LivrosPreco);

        P_AutorGenero.setText("Pesquisar autor pelo genero literario");
        P_AutorGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P_AutorGeneroActionPerformed(evt);
            }
        });
        jMenu3.add(P_AutorGenero);

        P_ConjugeAutor.setText("Pesquisar conjuge do autor/autora");
        P_ConjugeAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P_ConjugeAutorActionPerformed(evt);
            }
        });
        jMenu3.add(P_ConjugeAutor);

        P_AutorDataNasc.setText("Pesquisar por data de nascimento");
        P_AutorDataNasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P_AutorDataNascActionPerformed(evt);
            }
        });
        jMenu3.add(P_AutorDataNasc);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Validar");

        DTD_Autores.setText("DTD_Autores");
        DTD_Autores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DTD_AutoresActionPerformed(evt);
            }
        });
        jMenu4.add(DTD_Autores);

        XSD_Autores.setText("XSD_Autores");
        XSD_Autores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XSD_AutoresActionPerformed(evt);
            }
        });
        jMenu4.add(XSD_Autores);

        DTD_Obras.setText("DTD_Obras");
        DTD_Obras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DTD_ObrasActionPerformed(evt);
            }
        });
        jMenu4.add(DTD_Obras);

        XSD_Obras.setText("XSD_Obras");
        XSD_Obras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XSD_ObrasActionPerformed(evt);
            }
        });
        jMenu4.add(XSD_Obras);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("XSLT");
        jMenuBar1.add(jMenu5);

        jMenu6.setText("XQuery");
        jMenuBar1.add(jMenu6);

        jMenu7.setText("Ajuda");

        jMenuItem15.setText("Exemplos de autores");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem15);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ButtonAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(5, 5, 5)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ButtonAdd)
                            .addComponent(ButtonEliminar)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RelatorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RelatorioActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        try {
            String textoAux = FuncAuxs.lerFicheiro("escritores.txt");
            jTextArea1.setText(textoAux);

        } catch (IOException ex) {
            Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void InicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InicioActionPerformed

    }//GEN-LAST:event_InicioActionPerformed

    private void AutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AutoresActionPerformed

        String nomeAux = ("Micael Eid - 2019112744"
                + "\nBruno Oliveira - 2019136478");
        jTextArea1.setText(nomeAux);


    }//GEN-LAST:event_AutoresActionPerformed

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SairActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void ButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAddActionPerformed
        try {

            String nome = jTextField1.getText();

            if ("".equals(nome)) {
                Warnings.setVisible(false);
                JOptionPane.showMessageDialog(this,
                        "Insira um nome!",
                        "Aviso",
                        JOptionPane.INFORMATION_MESSAGE);
            } else {

                Autor au = WrappersWikipedia.criaAutor(nome);

                Document doc = XMLJDomFunctions.lerDocumentoXML("autores.xml");

                if (AchaNome(nome, doc)) {
                    Warnings.setVisible(false);
                    JOptionPane.showMessageDialog(this,
                            "Autor ja existe",
                            "Informação",
                            JOptionPane.INFORMATION_MESSAGE);

                    return;
                }

                doc = ModeloXML.adicionaAutor(au, doc);

                XMLJDomFunctions.escreverDocumentoParaFicheiro(doc, "autores.xml");

                Warnings.setVisible(false);
                JOptionPane.showMessageDialog(this,
                        "Autor adicionado com sucesso",
                        "Informação",
                        JOptionPane.INFORMATION_MESSAGE);

                ADO.setSize(290, 220);
                ADO.setLocation(500, 300);
                ADO.setTitle("Adicionar obra");
                ADO.setVisible(true);

            }

            //jDialog1.setVisible(false);
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
            Warnings.setVisible(false);
            JOptionPane.showMessageDialog(this,
                    "Erro ao Adicionar um autor",
                    "Aviso",
                    JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);

        }
    }//GEN-LAST:event_ButtonAddActionPerformed

    private void Menu_XMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_XMLActionPerformed

    }//GEN-LAST:event_Menu_XMLActionPerformed

    private void Obras_XMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Obras_XMLActionPerformed
        Document doc = XMLJDomFunctions.lerDocumentoXML("obras.xml");
        String texto = XMLJDomFunctions.escreverDocumentoString(doc);

        jTextArea1.setText(texto);
    }//GEN-LAST:event_Obras_XMLActionPerformed

    private void Autores_XMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Autores_XMLActionPerformed
        Document doc = XMLJDomFunctions.lerDocumentoXML("autores.xml");
        String texto = XMLJDomFunctions.escreverDocumentoString(doc);

        jTextArea1.setText(texto);
    }//GEN-LAST:event_Autores_XMLActionPerformed

    private void ButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEliminarActionPerformed
        String nome = jTextField1.getText();

        if ("".equals(nome)) {
            Warnings.setVisible(false);
            JOptionPane.showMessageDialog(this,
                    "Insira um nome!",
                    "Aviso",
                    JOptionPane.INFORMATION_MESSAGE);
        } else {
            Document doc = XMLJDomFunctions.lerDocumentoXML("autores.xml");

            if (doc == null) {

                Warnings.setVisible(false);
                JOptionPane.showMessageDialog(this,
                        "Ficheiro nao encontrado",
                        "Aviso",
                        JOptionPane.ERROR_MESSAGE);

            } else if (doc != null) {
                doc = ModeloXML.removeAutorNome(nome, doc);
                XMLJDomFunctions.escreverDocumentoParaFicheiro(doc, "autores.xml");

                Warnings.setVisible(false);
                JOptionPane.showMessageDialog(this,
                        "Autor removido com sucesso",
                        "Informação",
                        JOptionPane.INFORMATION_MESSAGE);
            } else {
                Warnings.setVisible(false);
                JOptionPane.showMessageDialog(this,
                        "Nome invalido",
                        "Aviso",
                        JOptionPane.ERROR_MESSAGE);
            }
        }


    }//GEN-LAST:event_ButtonEliminarActionPerformed

    private void DTD_AutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DTD_AutoresActionPerformed
        try {
            // TODO add your handling code here:
            int res = Validacao.validarDocumentoDTD("autores.xml", "autores.dtd");
            if (res == 1) {
                JOptionPane.showMessageDialog(this,
                        "Ficheiro válido por DTD",
                        "Validação DTD",
                        JOptionPane.INFORMATION_MESSAGE);
            }
            if (res == -1) {
                JOptionPane.showMessageDialog(this,
                        "Ficheiro inválido por DTD",
                        "Validação DTD",
                        JOptionPane.ERROR_MESSAGE);
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this,
                    "Verifique se os ficheiros XML e DTD existem",
                    "Validação DTD",
                    JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_DTD_AutoresActionPerformed

    private void XSD_AutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XSD_AutoresActionPerformed
        // TODO add your handling code here:
        int res = Validacao.validarDocumentoXSD("autores.xml", "autores.xsd");
        if (res == -1) {

            Warnings.setVisible(false);
            JOptionPane.showMessageDialog(this,
                    "O Ficheiro e valido",
                    "Validacao XSD",
                    JOptionPane.INFORMATION_MESSAGE);
        } else {

            Warnings.setVisible(false);
            JOptionPane.showMessageDialog(this,
                    "O Ficheiro e invalido",
                    "Validacao XSD",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_XSD_AutoresActionPerformed

    private void DTD_ObrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DTD_ObrasActionPerformed
        try {
            // TODO add your handling code here:
            int res = Validacao.validarDocumentoDTD("obras.xml", "obras.dtd");
            if (res == 1) {
                JOptionPane.showMessageDialog(this,
                        "Ficheiro válido por DTD",
                        "Validação DTD",
                        JOptionPane.INFORMATION_MESSAGE);
            }
            if (res == -1) {
                JOptionPane.showMessageDialog(this,
                        "Ficheiro inválido por DTD",
                        "Validação DTD",
                        JOptionPane.ERROR_MESSAGE);
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this,
                    "Verifique se os ficheiros XML e DTD existem",
                    "Validação DTD",
                    JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_DTD_ObrasActionPerformed

    private void XSD_ObrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XSD_ObrasActionPerformed
        int res = Validacao.validarDocumentoXSD("obras.xml", "obras.xsd");
        if (res == -1) {

            Warnings.setVisible(false);
            JOptionPane.showMessageDialog(this,
                    "O Ficheiro e valido",
                    "Validacao XSD",
                    JOptionPane.INFORMATION_MESSAGE);
        } else {

            Warnings.setVisible(false);
            JOptionPane.showMessageDialog(this,
                    "O Ficheiro e invalido",
                    "Validacao XSD",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_XSD_ObrasActionPerformed

    private void AlterarDataNascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterarDataNascActionPerformed

        ADN.setSize(450, 300);
        ADN.setLocation(500, 300);
        ADN.setTitle("Alterar Data Nascimento");
        ADN.setVisible(true);
    }//GEN-LAST:event_AlterarDataNascActionPerformed

    private void ADN_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADN_BActionPerformed
        Document doc = XMLJDomFunctions.lerDocumentoXML("autores.xml");

        doc = ModeloXML.alterarDataNasc(ADN_TF1.getText(), ADN_TF2.getText(), doc);

        JOptionPane.showMessageDialog(this,
                "Data alterada com sucesso",
                "Informação",
                JOptionPane.INFORMATION_MESSAGE);

        //grava o ficheiro XML em disco
        if (doc != null) {
            XMLJDomFunctions.escreverDocumentoParaFicheiro(doc, "autores.xml");
        } else {
            JOptionPane.showMessageDialog(this,
                    "Autor não foi encontrado",
                    "Informação",
                    JOptionPane.INFORMATION_MESSAGE);
        }
        ADN.setVisible(false);
    }//GEN-LAST:event_ADN_BActionPerformed

    private void ANC_TF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ANC_TF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ANC_TF1ActionPerformed

    private void ANC_B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ANC_B1ActionPerformed
        Document doc = XMLJDomFunctions.lerDocumentoXML("autores.xml");

        doc = ModeloXML.alterarNacionalidade(ANC_TF1.getText(), ANC_TF2.getText(), doc);

        JOptionPane.showMessageDialog(this,
                "Nacionalidade alterada com sucesso",
                "Informação",
                JOptionPane.INFORMATION_MESSAGE);

        //grava o ficheiro XML em disco
        if (doc != null) {
            XMLJDomFunctions.escreverDocumentoParaFicheiro(doc, "autores.xml");
        } else {
            JOptionPane.showMessageDialog(this,
                    "Autor não foi encontrado",
                    "Informação",
                    JOptionPane.INFORMATION_MESSAGE);
        }
        ANC.setVisible(false);
    }//GEN-LAST:event_ANC_B1ActionPerformed

    private void AlterarNacionalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterarNacionalidadeActionPerformed
        ANC.setSize(450, 300);
        ANC.setLocation(500, 300);
        ANC.setTitle("Alterar Nacionalidade");
        ANC.setVisible(true);
    }//GEN-LAST:event_AlterarNacionalidadeActionPerformed

    private void ACJ_TF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACJ_TF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ACJ_TF1ActionPerformed

    private void ACJ_B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACJ_B1ActionPerformed
        Document doc = XMLJDomFunctions.lerDocumentoXML("autores.xml");

        doc = ModeloXML.alterarConjuge(ACJ_TF1.getText(), ACJ_TF2.getText(), doc);

        JOptionPane.showMessageDialog(this,
                "Conjuge alterado com sucesso",
                "Informação",
                JOptionPane.INFORMATION_MESSAGE);

        //grava o ficheiro XML em disco
        if (doc != null) {
            XMLJDomFunctions.escreverDocumentoParaFicheiro(doc, "autores.xml");
        } else {
            JOptionPane.showMessageDialog(this,
                    "Autor não foi encontrado",
                    "Informação",
                    JOptionPane.INFORMATION_MESSAGE);
        }
        ACJ.setVisible(false);
    }//GEN-LAST:event_ACJ_B1ActionPerformed

    private void AlterarConjugeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterarConjugeActionPerformed
        ACJ.setSize(450, 300);
        ACJ.setLocation(500, 300);
        ACJ.setTitle("Alterar Conjuge");
        ACJ.setVisible(true);
    }//GEN-LAST:event_AlterarConjugeActionPerformed

    private void AGL_TF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AGL_TF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AGL_TF1ActionPerformed

    private void AGL_B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AGL_B1ActionPerformed
        Document doc = XMLJDomFunctions.lerDocumentoXML("autores.xml");

        doc = ModeloXML.alterarGeneroLit(AGL_TF1.getText(), AGL_TF2.getText(), doc);

        JOptionPane.showMessageDialog(this,
                "Genero Literario alterado com sucesso",
                "Informação",
                JOptionPane.INFORMATION_MESSAGE);

        //grava o ficheiro XML em disco
        if (doc != null) {
            XMLJDomFunctions.escreverDocumentoParaFicheiro(doc, "autores.xml");
        } else {
            JOptionPane.showMessageDialog(this,
                    "Autor não foi encontrado",
                    "Informação",
                    JOptionPane.INFORMATION_MESSAGE);
        }
        AGL.setVisible(false);
    }//GEN-LAST:event_AGL_B1ActionPerformed

    private void AlterarGeneroLitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterarGeneroLitActionPerformed
        AGL.setSize(450, 300);
        AGL.setLocation(500, 300);
        AGL.setTitle("Alterar Genero Literario");
        AGL.setVisible(true);
    }//GEN-LAST:event_AlterarGeneroLitActionPerformed

    private void P_InfoAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P_InfoAutorActionPerformed
        PIA.setSize(700, 550);
        PIA.setLocation(500, 300);
        PIA.setTitle("Pesquisar informações do Autor");
        PIA.setVisible(true);

    }//GEN-LAST:event_P_InfoAutorActionPerformed

    private void PIA_TF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PIA_TF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PIA_TF1ActionPerformed

    private void PIA_B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PIA_B1ActionPerformed
        try {
            String xp = "//autor[nome = " + "'" + PIA_TF1.getText() + "'" + "]/*";

            XdmValue res = XPathFunctions.executaXpath(xp, "autores.xml");
            String s = XPathFunctions.listaResultado(res);
            if (res == null) {
                PIA_TA1.setText("Ficheiro nao existe");

            } else if (res.size() == 0) {
                PIA_TA1.setText("Pesquisa sem resultados");
            } else {
                PIA_TA1.setText(s);
            }
        } catch (SaxonApiException ex) {
            Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_PIA_B1ActionPerformed

    private void PIN_TF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PIN_TF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PIN_TF1ActionPerformed

    private void PIN_B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PIN_B1ActionPerformed
        try {
            String xp = "//autor[nacionalidade = " + "'" + PIN_TF1.getText() + "'" + "]/nome";

            XdmValue res = XPathFunctions.executaXpath(xp, "autores.xml");
            String s = XPathFunctions.listaResultado(res);
            if (res == null) {
                PIN_TA1.setText("Ficheiro nao existe");

            } else if (res.size() == 0) {
                PIN_TA1.setText("Pesquisa sem resultados");
            } else {
                PIN_TA1.setText(s);
            }
        } catch (SaxonApiException ex) {
            Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_PIN_B1ActionPerformed

    private void P_autorNacionalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P_autorNacionalidadeActionPerformed
        PIN.setSize(700, 550);
        PIN.setLocation(500, 300);
        PIN.setTitle("Pesquisar nome do autor/a pela nacionalidade");
        PIN.setVisible(true);
    }//GEN-LAST:event_P_autorNacionalidadeActionPerformed

    private void POA_TF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_POA_TF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_POA_TF1ActionPerformed

    private void POA_B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_POA_B1ActionPerformed
        try {
            String xp = "//livro[autor = " + "'" + POA_TF1.getText() + "'" + "]/titulo";

            XdmValue res = XPathFunctions.executaXpath(xp, "obras.xml");
            String s = XPathFunctions.listaResultado(res);
            if (res == null) {
                POA_TA1.setText("Ficheiro nao existe");

            } else if (res.size() == 0) {
                POA_TA1.setText("Pesquisa sem resultados");
            } else {
                POA_TA1.setText(s);
            }
        } catch (SaxonApiException ex) {
            Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_POA_B1ActionPerformed

    private void P_ObrasAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P_ObrasAutorActionPerformed
        POA.setSize(700, 550);
        POA.setLocation(500, 300);
        POA.setTitle("Pesquisar Obras do autor/a pelo nome");
        POA.setVisible(true);
    }//GEN-LAST:event_P_ObrasAutorActionPerformed

    private void PAP_B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PAP_B1ActionPerformed
        try {
            String xp = "//autor[count(premios/premio) = max(//autor/count(premios/premio))]/nome";

            XdmValue res = XPathFunctions.executaXpath(xp, "autores.xml");
            String s = XPathFunctions.listaResultado(res);

            if (res == null) {
                PAP_TA1.setText("Ficheiro nao existe");

            } else if (res.size() == 0) {
                PAP_TA1.setText("Pesquisa sem resultados");
            } else {
                PAP_TA1.setText(s);
            }
        } catch (SaxonApiException ex) {
            Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_PAP_B1ActionPerformed

    private void P_AutorPremiadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P_AutorPremiadoActionPerformed
        PAP.setSize(700, 550);
        PAP.setLocation(500, 300);
        PAP.setTitle("Pesquisar autor mais premiado");
        PAP.setVisible(true);
    }//GEN-LAST:event_P_AutorPremiadoActionPerformed

    private void PPL_TF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PPL_TF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PPL_TF1ActionPerformed

    private void PPL_B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PPL_B1ActionPerformed
        try {
            String xp = "//obras/livro[preco >= " + PPL_TF1.getText() + "]/titulo";

            XdmValue res = XPathFunctions.executaXpath(xp, "obras.xml");
            String s = XPathFunctions.listaResultado(res);

            if (res == null) {
                PPL_TA1.setText("Ficheiro nao existe");

            } else if (res.size() == 0) {
                PPL_TA1.setText("Pesquisa sem resultados");
            } else {
                PPL_TA1.setText(s);
            }
        } catch (SaxonApiException ex) {
            Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_PPL_B1ActionPerformed

    private void P_LivrosPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P_LivrosPrecoActionPerformed
        PPL.setSize(700, 550);
        PPL.setLocation(500, 300);
        PPL.setTitle("Pesquisar livro por preço");
        PPL.setVisible(true);
    }//GEN-LAST:event_P_LivrosPrecoActionPerformed

    private void PGL_TF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PGL_TF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PGL_TF1ActionPerformed

    private void PGL_B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PGL_B1ActionPerformed
        try {
            String xp = "//autor[generoLiterario = " + "'" + PGL_TF1.getText() + "'" + "]/nome";

            XdmValue res = XPathFunctions.executaXpath(xp, "autores.xml");
            String s = XPathFunctions.listaResultado(res);

            if (res == null) {
                PGL_TA1.setText("Ficheiro nao existe");

            } else if (res.size() == 0) {
                PGL_TA1.setText("Pesquisa sem resultados");
            } else {
                PGL_TA1.setText(s);
            }
        } catch (SaxonApiException ex) {
            Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_PGL_B1ActionPerformed

    private void P_AutorGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P_AutorGeneroActionPerformed
        PGL.setSize(700, 550);
        PGL.setLocation(500, 300);
        PGL.setTitle("Pesquisar autor/a pelo genero literario");
        PGL.setVisible(true);
    }//GEN-LAST:event_P_AutorGeneroActionPerformed

    private void PPC_TF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PPC_TF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PPC_TF1ActionPerformed

    private void PPC_B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PPC_B1ActionPerformed
        try {
            String xp = "//autor[nome = " + "'" + PPC_TF1.getText() + "'" + "]/conjuge";

            XdmValue res = XPathFunctions.executaXpath(xp, "autores.xml");
            String s = XPathFunctions.listaResultado(res);

            if (res == null) {
                PPC_TA1.setText("Ficheiro nao existe");

            } else if (res.size() == 0) {
                PPC_TA1.setText("Pesquisa sem resultados");
            } else {
                PPC_TA1.setText(s);
            }
        } catch (SaxonApiException ex) {
            Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_PPC_B1ActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void P_AutorDataNascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P_AutorDataNascActionPerformed
        PDN.setSize(700, 550);
        PDN.setLocation(500, 300);
        PDN.setTitle("Pesquisar autor/a pela data de nascimento");
        PDN.setVisible(true);
    }//GEN-LAST:event_P_AutorDataNascActionPerformed

    private void PDN_TF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PDN_TF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PDN_TF1ActionPerformed

    private void PDN_B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PDN_B1ActionPerformed
        try {
            String xp = "//autor[dataNascimento = " + "'" + PDN_TF1.getText() + "'" + "]/nome";

            XdmValue res = XPathFunctions.executaXpath(xp, "autores.xml");
            String s = XPathFunctions.listaResultado(res);

            if (res == null) {
                PDN_TA1.setText("Ficheiro nao existe");

            } else if (res.size() == 0) {
                PDN_TA1.setText("Pesquisa sem resultados");
            } else {
                PDN_TA1.setText(s);
            }
        } catch (SaxonApiException ex) {
            Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_PDN_B1ActionPerformed

    private void P_ConjugeAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P_ConjugeAutorActionPerformed
        PPC.setSize(700, 550);
        PPC.setLocation(500, 300);
        PPC.setTitle("Pesquisar o conjuge pelo nome do autor");
        PPC.setVisible(true);
    }//GEN-LAST:event_P_ConjugeAutorActionPerformed

    private void ACP_TF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACP_TF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ACP_TF1ActionPerformed

    private void ACP_B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACP_B1ActionPerformed
        Document doc = XMLJDomFunctions.lerDocumentoXML("autores.xml");

        doc = ModeloXML.adicionaPremio(ACP_TF1.getText(), ACP_TF2.getText(), doc);

        JOptionPane.showMessageDialog(this,
                "Premio adicionado com sucesso",
                "Informação",
                JOptionPane.INFORMATION_MESSAGE);

        //grava o ficheiro XML em disco
        if (doc != null) {
            XMLJDomFunctions.escreverDocumentoParaFicheiro(doc, "autores.xml");
        } else {
            JOptionPane.showMessageDialog(this,
                    "Autor não foi encontrado",
                    "Informação",
                    JOptionPane.INFORMATION_MESSAGE);
        }
        ACP.setVisible(false);
    }//GEN-LAST:event_ACP_B1ActionPerformed

    private void AcrescentarPremioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcrescentarPremioActionPerformed
        ACP.setSize(450, 300);
        ACP.setLocation(500, 300);
        ACP.setTitle("Adicionar Premio");
        ACP.setVisible(true);
    }//GEN-LAST:event_AcrescentarPremioActionPerformed

    private void RMP_TF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RMP_TF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RMP_TF1ActionPerformed

    private void RMP_B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RMP_B1ActionPerformed
        Document doc = XMLJDomFunctions.lerDocumentoXML("autores.xml");

        doc = ModeloXML.removePremio(RMP_TF1.getText(), RMP_TF2.getText(), doc);

        JOptionPane.showMessageDialog(this,
                "Premio removido com sucesso",
                "Informação",
                JOptionPane.INFORMATION_MESSAGE);

        //grava o ficheiro XML em disco
        if (doc != null) {
            XMLJDomFunctions.escreverDocumentoParaFicheiro(doc, "autores.xml");
        } else {
            JOptionPane.showMessageDialog(this,
                    "Autor não foi encontrado",
                    "Informação",
                    JOptionPane.INFORMATION_MESSAGE);
        }
        RMP.setVisible(false);
    }//GEN-LAST:event_RMP_B1ActionPerformed

    private void EliminaPremioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminaPremioActionPerformed
        RMP.setSize(450, 300);
        RMP.setLocation(500, 300);
        RMP.setTitle("Remover Premio");
        RMP.setVisible(true);
    }//GEN-LAST:event_EliminaPremioActionPerformed

    private void ADO_B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADO_B1ActionPerformed
        if (!"".equals(ADO_TF1.getText()) && !"0".equals(ADO_TF1.getText())) {
            try {
                ArrayList<Obras> obs = new ArrayList<>();
                ArrayList<String> linkObras = WrappersBertrand.obtem_link(jTextField1.getText(), Integer.parseInt(ADO_TF1.getText()));

                for (int i = 0; i < linkObras.size(); i++) {
                    obs.add(WrappersBertrand.criaObras(linkObras.get(i)));
                }

                Document doc2 = XMLJDomFunctions.lerDocumentoXML("obras.xml");

                doc2 = ModeloXML.adicionaObra(obs, doc2);

                XMLJDomFunctions.escreverDocumentoParaFicheiro(doc2, "obras.xml");

                Warnings.setVisible(false);
                JOptionPane.showMessageDialog(this,
                        "Obra/as adicionada/as com sucesso",
                        "Informação",
                        JOptionPane.INFORMATION_MESSAGE);
            } catch (IOException ex) {
                Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
            }

        }else{
            ADO.setVisible(false);
        }
    }//GEN-LAST:event_ADO_B1ActionPerformed

    private void ADN_TF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADN_TF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADN_TF1ActionPerformed

    private void ADO_TF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADO_TF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADO_TF1ActionPerformed

    private void RMO_B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RMO_B1ActionPerformed
         String titulo = RMO_TF1.getText();

        if ("".equals(titulo)) {
            Warnings.setVisible(false);
            JOptionPane.showMessageDialog(this,
                    "Insira um titulo!",
                    "Aviso",
                    JOptionPane.INFORMATION_MESSAGE);
        } else {
            Document doc = XMLJDomFunctions.lerDocumentoXML("obras.xml");

            if (doc == null) {

                Warnings.setVisible(false);
                JOptionPane.showMessageDialog(this,
                        "Ficheiro nao encontrado",
                        "Aviso",
                        JOptionPane.ERROR_MESSAGE);

            } else if (doc != null) {
                doc = ModeloXML.removeLivroTitulo(titulo, doc);
                XMLJDomFunctions.escreverDocumentoParaFicheiro(doc, "obras.xml");

                Warnings.setVisible(false);
                JOptionPane.showMessageDialog(this,
                        "Obra removida com sucesso",
                        "Informação",
                        JOptionPane.INFORMATION_MESSAGE);
            } else {
                Warnings.setVisible(false);
                JOptionPane.showMessageDialog(this,
                        "Titulo invalido",
                        "Aviso",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
        
        RMO.setVisible(false);
    }//GEN-LAST:event_RMO_B1ActionPerformed

    private void RMO_TF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RMO_TF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RMO_TF1ActionPerformed

    private void EliminarObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarObraActionPerformed
        RMO.setSize(280, 200);
        RMO.setLocation(500, 300);
        RMO.setTitle("Remover Obra");
        RMO.setVisible(true);
    }//GEN-LAST:event_EliminarObraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog ACJ;
    private javax.swing.JButton ACJ_B1;
    private javax.swing.JLabel ACJ_L1;
    private javax.swing.JLabel ACJ_L2;
    private javax.swing.JTextField ACJ_TF1;
    private javax.swing.JTextField ACJ_TF2;
    private javax.swing.JDialog ACP;
    private javax.swing.JButton ACP_B1;
    private javax.swing.JLabel ACP_L1;
    private javax.swing.JLabel ACP_L2;
    private javax.swing.JTextField ACP_TF1;
    private javax.swing.JTextField ACP_TF2;
    private javax.swing.JDialog ADN;
    private javax.swing.JButton ADN_B;
    private javax.swing.JLabel ADN_Label1;
    private javax.swing.JLabel ADN_Lebal2;
    private javax.swing.JTextField ADN_TF1;
    private javax.swing.JTextField ADN_TF2;
    private javax.swing.JDialog ADO;
    private javax.swing.JButton ADO_B1;
    private javax.swing.JLabel ADO_L1;
    private javax.swing.JLabel ADO_L2;
    private javax.swing.JTextField ADO_TF1;
    private javax.swing.JDialog AGL;
    private javax.swing.JButton AGL_B1;
    private javax.swing.JLabel AGL_L1;
    private javax.swing.JLabel AGL_L2;
    private javax.swing.JTextField AGL_TF1;
    private javax.swing.JTextField AGL_TF2;
    private javax.swing.JDialog ANC;
    private javax.swing.JButton ANC_B1;
    private javax.swing.JLabel ANC_Label1;
    private javax.swing.JLabel ANC_Label2;
    private javax.swing.JTextField ANC_TF1;
    private javax.swing.JTextField ANC_TF2;
    private javax.swing.JMenuItem AcrescentarPremio;
    private javax.swing.JMenuItem AlterarConjuge;
    private javax.swing.JMenuItem AlterarDataNasc;
    private javax.swing.JMenuItem AlterarGeneroLit;
    private javax.swing.JMenuItem AlterarNacionalidade;
    private javax.swing.JMenuItem Autores;
    private javax.swing.JMenuItem Autores_XML;
    private javax.swing.JButton ButtonAdd;
    private javax.swing.JButton ButtonEliminar;
    private javax.swing.JMenuItem DTD_Autores;
    private javax.swing.JMenuItem DTD_Obras;
    private javax.swing.JMenuItem EliminaPremio;
    private javax.swing.JMenuItem EliminarObra;
    private javax.swing.JMenu Inicio;
    private javax.swing.JMenu Menu_XML;
    private javax.swing.JMenuItem Obras_XML;
    private javax.swing.JDialog PAP;
    private javax.swing.JButton PAP_B1;
    private javax.swing.JTextArea PAP_TA1;
    private javax.swing.JDialog PDN;
    private javax.swing.JButton PDN_B1;
    private javax.swing.JLabel PDN_L1;
    private javax.swing.JTextArea PDN_TA1;
    private javax.swing.JTextField PDN_TF1;
    private javax.swing.JDialog PGL;
    private javax.swing.JButton PGL_B1;
    private javax.swing.JLabel PGL_L1;
    private javax.swing.JTextArea PGL_TA1;
    private javax.swing.JTextField PGL_TF1;
    private javax.swing.JDialog PIA;
    private javax.swing.JButton PIA_B1;
    private javax.swing.JLabel PIA_L1;
    private javax.swing.JTextArea PIA_TA1;
    private javax.swing.JTextField PIA_TF1;
    private javax.swing.JDialog PIN;
    private javax.swing.JButton PIN_B1;
    private javax.swing.JLabel PIN_L1;
    private javax.swing.JTextArea PIN_TA1;
    private javax.swing.JTextField PIN_TF1;
    private javax.swing.JDialog POA;
    private javax.swing.JButton POA_B1;
    private javax.swing.JLabel POA_L1;
    private javax.swing.JTextArea POA_TA1;
    private javax.swing.JTextField POA_TF1;
    private javax.swing.JDialog PPC;
    private javax.swing.JButton PPC_B1;
    private javax.swing.JLabel PPC_L1;
    private javax.swing.JTextArea PPC_TA1;
    private javax.swing.JTextField PPC_TF1;
    private javax.swing.JDialog PPL;
    private javax.swing.JButton PPL_B1;
    private javax.swing.JLabel PPL_L1;
    private javax.swing.JTextArea PPL_TA1;
    private javax.swing.JTextField PPL_TF1;
    private javax.swing.JMenuItem P_AutorDataNasc;
    private javax.swing.JMenuItem P_AutorGenero;
    private javax.swing.JMenuItem P_AutorPremiado;
    private javax.swing.JMenuItem P_ConjugeAutor;
    private javax.swing.JMenuItem P_InfoAutor;
    private javax.swing.JMenuItem P_LivrosPreco;
    private javax.swing.JMenuItem P_ObrasAutor;
    private javax.swing.JMenuItem P_autorNacionalidade;
    private javax.swing.JDialog RMO;
    private javax.swing.JButton RMO_B1;
    private javax.swing.JLabel RMO_L1;
    private javax.swing.JTextField RMO_TF1;
    private javax.swing.JDialog RMP;
    private javax.swing.JButton RMP_B1;
    private javax.swing.JLabel RMP_L1;
    private javax.swing.JLabel RMP_L2;
    private javax.swing.JTextField RMP_TF1;
    private javax.swing.JTextField RMP_TF2;
    private javax.swing.JMenuItem Relatorio;
    private javax.swing.JMenuItem Sair;
    private javax.swing.JDialog Warnings;
    private javax.swing.JMenuItem XSD_Autores;
    private javax.swing.JMenuItem XSD_Obras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
